import { BusinessDirectory } from "../ui/components/admin/BusinessDirectory";
import type { Business } from "../ui/components/types/admin.types";

const MOCK: Business[] = [
  {
    id: "1",
    name: "Bella's Italian Bistro",
    category: "Restaurant",
    location: "Central Business District",
    avatarUrl: "",
    tags: ["Restaurant", "Verified", "Premium"],
    submittedAt: new Date().toISOString(),
    owner: "Isabella Rodriguez",
    status: "active",
    address: "123 Main Street, Central Business District",
    zone: "Central Business District",
    verification: ["verified", "premium"],
    meta: { rating: 4.8, reviewsCount: 124, lastUpdated: new Date().toISOString(), monthlyViews: 1247 },
  },
  {
    id: "2",
    name: "TechFix Solutions",
    category: "Tech Services",
    location: "North Quarter",
    avatarUrl: "",
    tags: ["Tech"],
    submittedAt: new Date().toISOString(),
    owner: "Mike Chen",
    status: "pending",
    address: "456 Oak Avenue, North Quarter",
    zone: "North Quarter",
    verification: ["basic"],
    meta: { lastUpdated: new Date().toISOString() },
  },
  {
    id: "3",
    name: "Green Leaf Pharmacy",
    category: "Healthcare",
    location: "West Hills",
    avatarUrl: "",
    tags: ["Healthcare", "Verified"],
    submittedAt: new Date().toISOString(),
    owner: "Sarah Johnson",
    status: "active",
    address: "789 Pine Street, West Hills",
    zone: "West Hills",
    verification: ["verified"],
    meta: { rating: 4.9, reviewsCount: 89, lastUpdated: new Date().toISOString(), monthlyViews: 892 },
  },
  {
    id: "4",
    name: "Urban Threads Boutique",
    category: "Fashion Retail",
    location: "Central Business District",
    avatarUrl: "",
    tags: ["Fashion"],
    submittedAt: new Date().toISOString(),
    owner: "Amanda Foster",
    status: "suspended",
    address: "321 Fashion Avenue, Central Business District",
    zone: "Central Business District",
    verification: ["unverified"],
    meta: { lastUpdated: new Date().toISOString() },
  },
  {
    id: "5",
    name: "Downtown Dental Care",
    category: "Healthcare",
    location: "Central Business District",
    avatarUrl: "",
    tags: ["Healthcare", "Verified", "Premium"],
    submittedAt: new Date().toISOString(),
    owner: "Dr. Robert Kim",
    status: "active",
    address: "567 Medical Plaza, Central Business District",
    zone: "Central Business District",
    verification: ["verified", "premium"],
    meta: { rating: 4.7, reviewsCount: 156, lastUpdated: new Date().toISOString(), monthlyViews: 2134 },
  },
];

export default function AdminDirectoryDemo() {
  return <BusinessDirectory data={MOCK} />;
}
